---
title: "Christina_clean"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(dplyr)
```


Whole dataset
```{r}
cancer_data <- read.table('data.csv', header = TRUE, sep = ";", quote = "", check.names = FALSE)

cancer_data_tibble <- as_tibble(cancer_data)
  
# Clean and standardize column names 
cancer_data_tibble <- cancer_data_tibble |>
  rename_all(tolower) |>
  rename_all(~ gsub("[^[:alnum:]]", " ", .))  # Replace non-alphanumeric characters with underscores

# Remove quotation marks from all columns
cancer_data_tibble[] <- lapply(cancer_data_tibble, function(x) gsub('"', '', x))


# Display the tibble to check the changes
#print(cancer_data_tibble)
  
```




Seperated dataset: First part 
```{r}
cancer_data_1 <- read.table('data_1.csv', header = TRUE, sep = ",", quote = "", check.names = FALSE)

cancer_data_1_tibble <- as_tibble(cancer_data_1)
  
# Clean and standardize column names 
cancer_data_1_tibble <- cancer_data_1_tibble |>
  rename_all(tolower) |>
  rename_all(~ gsub("[^[:alnum:]]", " ", .))  # Replace non-alphanumeric characters with underscores

# Remove quotation marks from all columns
cancer_data_1_tibble[] <- lapply(cancer_data_1_tibble, function(x) gsub('"', '', x))


# Display the tibble to check the changes
print(cancer_data_1_tibble)

```

Second part:
```{r}
cancer_data_2 <- read.table('data_2.csv', header = TRUE, sep = ",", quote = "", check.names = FALSE)

cancer_data_2_tibble <- as_tibble(cancer_data_2)
  
# Clean and standardize column names 
cancer_data_2_tibble <- cancer_data_2_tibble |>
  rename_all(tolower) |>
  rename_all(~ gsub("[^[:alnum:]]", " ", .))  # Replace non-alphanumeric characters with underscores

# Remove quotation marks from all columns
cancer_data_2_tibble[] <- lapply(cancer_data_2_tibble, function(x) gsub('"', '', x))


# Display the tibble to check the changes
print(cancer_data_2_tibble)
```
```{r}
cancer_data_3 <- read.table('data_3.csv', header = TRUE, sep = ",", quote = "", check.names = FALSE)

cancer_data_3_tibble <- as_tibble(cancer_data_3)
  
# Clean and standardize column names 
cancer_data_3_tibble <- cancer_data_3_tibble |>
  rename_all(tolower) |>
  rename_all(~ gsub("[^[:alnum:]]", " ", .))  # Replace non-alphanumeric characters with underscores

# Remove quotation marks from all columns
cancer_data_3_tibble[] <- lapply(cancer_data_3_tibble, function(x) gsub('"', '', x))


# Display the tibble to check the changes
print(cancer_data_3_tibble)
```


