---
title: "visualisations"
format: html
editor: visual
---

## Reading the data

```{r}
cancer_dataset <- read_tsv('/home/people/s223094/project/Group_10_project/data/02_dat_clean.tsv')

cancer_dataset |>
  select(diagnosis) |>
  print()
```

## Visualizations

Making density plots of the parameters, based on benign or malignant

```{r}
# Customize boxplot
ggplot(data = cancer_dataset, 
       aes(y = `radius se`, fill = as.factor(diagnosis))) +
  
  geom_boxplot(alpha = 0.8, 
               color = "black", 
               size = 0.5) +
  
  scale_fill_manual(values = c("0" = "lightpink", "1" = "lightblue")) +
  labs( y = "Value", title = "Boxplot by Category") +
  theme_minimal() 
```

```{r}
set.seed(1234)

cancer_dataset_long <- gather(cancer_dataset, key = "Parameter", value = "Value", `radius se`, `texture se`, `perimeter se`, `area se`, `smoothness se`, `concavity se`, `concave points se`, `symmetry se`, `fractal dimension se`, `compactness se`)

# Standardize the values within each level of Parameter
cancer_dataset_long <- cancer_dataset_long %>%
  group_by(Parameter) %>%
  mutate(StandardizedValue = scale(Value))

# Customize boxplot
ggplot(data = cancer_dataset_long, 
       aes(x = Parameter, y = StandardizedValue, fill = as.factor(diagnosis))) +
  
  geom_boxplot(alpha = 0.8, 
               color = "black", 
               size = 0.2) +
  
  scale_fill_manual(values = c("0" = "lightpink", "1" = "lightblue")) +
  labs(x = "Parameter", y = "Standardized Value", title = "Boxplot by Category") +
  theme_minimal() +
  theme(
    plot.margin = margin(2, 1, 1, 1, "cm"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

Making violin plots of the parameters, based on benging or malignant

```{r}

```
